df <- mydata[, c(1,2,3,4)]
View(df)
cor(df)
regmodel <- lm(price ~ yearOfRegistration + powerPS + kilometer)
summary(regmodel)
regmodel <- lm(price ~ yearOfRegistration + powerPS)
summary(regmodel)
regmodel <- lm(price ~ yearOfRegistration + kilometer)
summary(regmodel)
regmodel <- lm(price ~ powerPS + kilometer)
summary(regmodel)
regmodel <- lm(price ~ yearOfRegistration)
summary(regmodel)
regmodel <- lm(price ~ powerPS)
summary(regmodel)
regmodel <- lm(price ~ kilometer)
summary(regmodel)
